apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: nbyvxe5hb-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/nbyvxe5hb-java-springboot-gitops